export const mockPosts = [
    {
      id: "1",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Just bought more #Bitcoin during this dip! 📉➡️📈 Remember, it's not about timing the market, it's about time IN the market. HODL strong, friends! 💎🙌 #Crypto #BTC #ToTheMoon",
      crypto: "Bitcoin",
      timestamp: "2h ago",
      likes: 3452,
      comments: 128,
      shares: 76,
      username: "BitcoinBaron",
      userHandle: "bitcoin_baron",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "2",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Ethereum's merge to proof-of-stake is a game changer for energy consumption! 🌱 The future of finance is green, scalable, and decentralized. Who's excited for ETH 2.0? #Ethereum #ETH #DeFi #Web3",
      crypto: "Ethereum",
      timestamp: "5h ago",
      likes: 2891,
      comments: 203,
      shares: 112,
      username: "EtherExplorer",
      userHandle: "ether_explorer",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "3",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Much wow! Very currency! 🐕 Dogecoin community is the best in crypto - change my mind! Thanks to everyone who participated in our charity fundraiser. We raised over 50,000 DOGE for animal shelters! #Dogecoin #DOGE #DoOnlyGoodEveryday",
      crypto: "Dogecoin",
      timestamp: "8h ago",
      likes: 5678,
      comments: 342,
      shares: 221,
      username: "DogeWhisperer",
      userHandle: "doge_whisperer",
      verified: false,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "4",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Solana throughput is INSANE! Just processed 500 transactions in under a minute for less than $0.01 in fees. This is what blockchain scalability looks like! 🚀 #Solana #SOL #Blockchain #TPS",
      crypto: "Solana",
      timestamp: "12h ago",
      likes: 1843,
      comments: 97,
      shares: 64,
      username: "SolanaSpeed",
      userHandle: "solana_speed",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "5",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Bitcoin halving is approaching! Historically, this has been followed by significant price appreciation. Are you ready for what's coming? 📊 #Bitcoin #BTCHalving #CryptoInvesting",
      crypto: "Bitcoin",
      timestamp: "1d ago",
      likes: 4210,
      comments: 156,
      shares: 98,
      username: "SatoshiStudent",
      userHandle: "satoshi_student",
      verified: false,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "6",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Just deployed my first smart contract on Ethereum! 🧠 The possibilities with this technology are endless. Who else is building on ETH? Let's connect! #Ethereum #SmartContracts #Solidity #DApp",
      crypto: "Ethereum",
      timestamp: "1d ago",
      likes: 2103,
      comments: 187,
      shares: 45,
      username: "CodeWithCrypto",
      userHandle: "code_crypto",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "7",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Dogecoin tipping is the future of social media appreciation! Just tipped my favorite content creators with DOGE. So easy, so fun! 🐕💰 #Dogecoin #CryptoTipping #ContentCreators",
      crypto: "Dogecoin",
      timestamp: "2d ago",
      likes: 3567,
      comments: 231,
      shares: 112,
      username: "TippingShibe",
      userHandle: "tipping_shibe",
      verified: false,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "8",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Building on Solana is a developer's dream! ⚡ The tooling, documentation, and community support are top-notch. Just launched my NFT marketplace with 0.4s transaction finality! #Solana #SolDev #NFTs",
      crypto: "Solana",
      timestamp: "2d ago",
      likes: 1932,
      comments: 104,
      shares: 87,
      username: "SolanaBuilder",
      userHandle: "solana_builder",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "9",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Bitcoin is digital real estate in cyberspace. Limited supply, growing demand. The hardest money ever created. 🏙️ #Bitcoin #DigitalGold #Scarcity",
      crypto: "Bitcoin",
      timestamp: "3d ago",
      likes: 5102,
      comments: 267,
      shares: 189,
      username: "BitcoinMaximalist",
      userHandle: "btc_maximalist",
      verified: true,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    {
      id: "10",
      imageUrl: "/placeholder.svg?height=600&width=800",
      caption:
        "Ethereum L2s are changing the game! Just used @Optimism and was blown away by the speed and low fees. The future of Ethereum scaling is here! 🔥 #Ethereum #Layer2 #Optimism #Scaling",
      crypto: "Ethereum",
      timestamp: "3d ago",
      likes: 2765,
      comments: 198,
      shares: 124,
      username: "L2Enthusiast",
      userHandle: "l2_enthusiast",
      verified: false,
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
  ]
  
  